name: "Skeleton"
services:
  playground:
    image: yingzhuo/java-application-skeleton-with-gradle-kotlin:latest
    restart: always
    container_name: skeleton
    ports:
      - "8080:8080"
    command:
      - "--spring.profiles.active=prod"
